name: coverity

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-coverity:
    runs-on: ubuntu-latest
    if: github.repository == 'iLCSoft/iLCUtil'
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@v3
      with:
        coverity-cmake-command: cmake -C ${ILCSOFT}/ILCSoft.cmake -DCMAKE_CXX_STANDARD=17 -DUSE_CXX11=OFF
        coverity-project: iLCSoft%2FiLCUtil
        coverity-project-token: ${{ secrets.ILCUTIL_COVERITY_TOKEN }}
        github-pat: ${{ secrets.READ_COVERITY_IMAGE }}
        view-path: /cvmfs/clicdp.cern.ch/iLCSoft/builds/current/CI_gcc
        setup-script: init_ilcsoft.sh
